version: '3'

name: 'bydigital-assist-local'
services:
  db:
    image: mariadb:10.6.4-focal
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=wordpresssecret
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    expose:
      - 3306
    networks:
      - backend

  wordpress:
    image: wordpress:latest
    volumes:
      - wp_data:/var/www/html
      - ./wp-content:/var/www/html/wp-content
    restart: always
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: ${DB_HOST:-db:3306}
      WORDPRESS_DB_USER: ${DB_USER:-wordpress}
      WORDPRESS_DB_PASSWORD: ${DB_PASS:-wordpress}
      WORDPRESS_DB_NAME: ${DB_NAME:-wordpress}
      WORDPRESS_CONFIG_EXTRA: |
          define('WP_SITEURL', 'http://' . $$_SERVER['HTTP_HOST']);
          define('WP_HOME', 'http://' . $$_SERVER['HTTP_HOST']);
    extra_hosts:
     - "${SITE_NAME}.local:127.0.0.1"
    hostname: ${SITE_NAME}.local
    domainname: local
    networks:
      - backend
    
volumes:
  db_data:
  wp_data:

networks:
  backend:
    driver: bridge